print("=== Unit Converter ===")
print()
print("TEMPERATURE")
fahrenheit = float(input("Enter a temperature in Fahrenheit: "))
print(f"{fahrenheit:.0f}°F = {(fahrenheit - 32) * (5/9):.2f}°C")
print()
celsius = float(input("Enter a temperature in Celsius: "))
print(f"{celsius:.0f}°C = {(celsius * (9/5)) + 32:.2f}°F")
print()
print("DISTANCE")
miles = float(input("Enter a distance in miles: "))
print(f"{miles} miles = {miles * 1.609344:.2f} kilometers")
print()
kilometers = float(input("Enter a distance in kilometers: "))
print(f"{kilometers} kilometers = {kilometers / 1.609344:.2f} miles")
print()
print("WEIGHT")
pounds = float(input("Enter a weight in pounds: "))
print(f"{pounds} lbs = {pounds * 0.453592:.2f} kg")
print()
kilograms = float(input("Enter a weight in kilograms: "))
print(f"{kilograms} kg = {kilograms / 0.453592:.2f} lbs")
print()
print("=== All conversions complete! ===")

