print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("|   Greetings, I am Shawn Christopher.   |")
print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print()
print("About me:")
print()
print("I started vibe-coding with Claude Code")
print("and realized I should probably learn how")
print('to write code the "proper" way to be able')
print("to check its work.")
print("Being a 90's baby, I am a little late to")
print("the game but I plan on devoting some")
print("serious hours to this.")
print()
print("TASK: Go from 0 to full-stack developer")
print("TIMELINE: 52 weeks")
print()
print("I'll give myself at least three hours a")
print("day, seven days a week. So ",21*52," hours.")
print("Minimum.")
print("Probably more.")
print("Definitely more.")
print()
print("Good luck, future-Chris!")
